#!/bin/bash

sudo apt update && sudo apt upgrade

#dualboot clock fix
sudo timedatectl set-local-rtc 1 --adjust-system-clock

#spotify
curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
sduo apt update && sudo apt install spotify-client -y

#Discord
cd ~/Downloads && curl -L "https://discord.com/api/download?platform=linux&format=deb" >> discord.deb
sudo apt install ./discord.deb


