#!/bin/bash
shopt -s expand_aliases
git clone --bare https://github.com/jurek-nky/.cfg $HOME/.cfg
alias config="git --git-dir=$HOME/.cfg/ --work-tree=$HOME"
config checkout
config config status.showUntrackedFiles no
