#!/bin/bash
shopt -s expand_aliases
git clone --bare git@github.com:Jurek-Nky/.cfg.git $HOME/.cfg
alias config="git --git-dir=$HOME/.cfg/ --work-tree=$HOME"
config checkout -f
config config status.showUntrackedFiles no
