#!/bin/bash
packagesNeeded='git zoxide wget exa doas fd-find dua-cli bat fish vim htop cargo speedtest-cli python3-keep'
if [ -x "$(command -v apk)" ];       then sudo apk add --no-cache $packagesNeeded
elif [ -x "$(command -v apt-get)" ]; then sudo apt-get install $packagesNeeded
elif [ -x "$(command -v dnf)" ];     then sudo dnf install $packagesNeeded
elif [ -x "$(command -v zypper)" ];  then sudo zypper install $packagesNeeded
else echo "FAILED TO INSTALL PACKAGE: Package manager not found. You must manually install: $packagesNeeded">&2; fi

cargoPackagesNeeded='rm-improved xcp'
cargo install $cargoPackagesNeeded
